import type { CSSProperties } from "react";

/** Co-located styles for PrBriefCard. Full-width, above the INTENT/BLAST
 *  RADIUS grid (AC-49) — unlike those two cards this one does not share a
 *  50% column, so none of their overflow-wrap defenses are needed here. */
export const s = {
  wrap: {
    marginBottom: 18,
    padding: "16px 18px",
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  titleGroup: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  modelBadge: {
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  loadingLine: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  errorWrap: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  whatWhy: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginBottom: 14,
  } satisfies CSSProperties,
  what: {
    fontSize: 14,
    color: "var(--text-primary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  why: {
    fontSize: 13.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 14,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskLevelRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
  } satisfies CSSProperties,
  riskLevelLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskLevelValue: (color: string): CSSProperties => ({
    fontSize: 13,
    fontWeight: 700,
    color,
  }),
  notice: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    marginBottom: 10,
  } satisfies CSSProperties,
  noticeWarn: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--warn, #b45309)",
    background: "var(--bg-surface)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    marginBottom: 10,
  } satisfies CSSProperties,
  noticeText: { flex: 1 } satisfies CSSProperties,
  section: {
    marginTop: 16,
  } satisfies CSSProperties,
  sectionHeading: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  riskList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  riskItem: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "10px 12px",
  } satisfies CSSProperties,
  riskHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  } satisfies CSSProperties,
  riskTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  riskExplanation: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    marginBottom: 6,
  } satisfies CSSProperties,
  riskRefs: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  focusList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  focusItem: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    fontSize: 13,
  } satisfies CSSProperties,
  focusIndex: {
    color: "var(--text-muted)",
    fontSize: 12,
    flexShrink: 0,
  } satisfies CSSProperties,
  /** Same reset + affordance idiom as BlastRadiusCard's `callerFileButton`. */
  focusFileButton: {
    background: "none",
    borderStyle: "none",
    padding: 0,
    font: "inherit",
    fontSize: "inherit",
    cursor: "pointer",
    color: "var(--accent-text)",
    textDecoration: "underline",
    textUnderlineOffset: 2,
    textAlign: "left",
  } satisfies CSSProperties,
  focusFileInert: {
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  focusReason: {
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  documentsRow: {
    marginTop: 14,
    fontSize: 12,
    color: "var(--text-muted)",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
  } satisfies CSSProperties,
  timelineWrap: {
    marginTop: 16,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  timelineHeading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  timelineList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  timelineItem: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 10px",
  } satisfies CSSProperties,
  timelineMetaRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  timelineWhat: {
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  timelineBadgeCurrent: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  timelineBadgeStale: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--warn, #b45309)",
  } satisfies CSSProperties,
} as const;
