import type { CSSProperties } from "react";
import { ROW_HEIGHT } from "./constants";

/** Co-located styles for ContextTab. Closely mirrors the sibling SkillsTab's
    `styles.ts` — same list/row/reorder shape, different trailing content
    (type badge + Preview button instead of a single type badge). */
export const s = {
  wrap: { maxWidth: 900 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 10 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700, letterSpacing: "-0.01em" } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginLeft: "auto",
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 220,
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 12.5,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-secondary)", marginBottom: 18, lineHeight: 1.5 } satisfies CSSProperties,

  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: (linked: boolean, dragging: boolean, dropBefore: boolean): CSSProperties => {
    const edge = linked ? "var(--border)" : "transparent";
    return {
      position: "relative",
      display: "flex",
      alignItems: "center",
      gap: 10,
      height: ROW_HEIGHT,
      padding: "0 10px 0 8px",
      borderRadius: 7,
      borderStyle: "solid",
      borderColor: dropBefore ? `var(--accent) ${edge} ${edge}` : edge,
      borderWidth: dropBefore ? "2px 1px 1px" : 1,
      background: linked ? "var(--bg-elevated)" : "var(--bg-surface)",
      opacity: dragging ? 0.4 : 1,
      transition: "background .12s, border-color .12s",
    };
  },
  handle: {
    display: "grid",
    placeItems: "center",
    width: 18,
    height: 18,
    flexShrink: 0,
    color: "var(--text-muted)",
    cursor: "grab",
  } satisfies CSSProperties,
  checkbox: (checked: boolean): CSSProperties => ({
    width: 15,
    height: 15,
    flexShrink: 0,
    borderRadius: 3,
    border: `1.5px solid ${checked ? "var(--accent)" : "var(--border-strong)"}`,
    background: checked ? "var(--accent)" : "transparent",
    display: "grid",
    placeItems: "center",
    padding: 0,
    cursor: "pointer",
  }),
  rowPath: (linked: boolean): CSSProperties => ({
    flex: 1,
    minWidth: 0,
    fontSize: 12.5,
    fontWeight: 500,
    color: linked ? "var(--text-primary)" : "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  rowPrefix: { color: "var(--text-muted)", fontWeight: 400 } satisfies CSSProperties,
  missingTag: {
    fontSize: 11,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    padding: "1px 6px",
    borderRadius: 4,
    flexShrink: 0,
  } satisfies CSSProperties,
  reorderOverlay: (visible: boolean): CSSProperties => ({
    position: "absolute",
    right: 170,
    display: "flex",
    alignItems: "center",
    gap: 2,
    opacity: visible ? 1 : 0,
    pointerEvents: visible ? "auto" : "none",
    transition: "opacity .12s",
  }),
  reorderBtn: (disabled: boolean): CSSProperties => ({
    display: "grid",
    placeItems: "center",
    width: 18,
    height: 18,
    padding: 0,
    border: "none",
    background: "none",
    color: "var(--text-muted)",
    opacity: disabled ? 0.3 : 1,
    cursor: disabled ? "not-allowed" : "pointer",
  }),
  typeBadge: {
    width: 70,
    flexShrink: 0,
    display: "flex",
    justifyContent: "flex-end",
  } satisfies CSSProperties,
  previewBtn: { flexShrink: 0 } satisfies CSSProperties,

  empty: { fontSize: 13, color: "var(--text-muted)", padding: "10px 4px" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  footerTokens: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  footerHint: { fontSize: 12, color: "var(--text-muted)", maxWidth: 420, textAlign: "right" } satisfies CSSProperties,
} as const;
